### ISSUE TITLE
citations

### ISSUE THREAD

**Issue by rebzzy** [georgeshirreff/multiNe#10]
Hey @ewersSaucedo,

What citations should I use for your scripts? LDNe is a re-implementation of Waples & Do 2008, but what about the others? Is the VarNe the Nei and Tajima 1981 or does it include modifications (Waples & Yokota 2007 or Jorde)? 

Thanks!

**Comment by EwersAquaGenomics** [comment]
Please include Jorde and Ryman 2007 in addition to Nei and Tajima 1981.

Thank you!
