### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by JuliaPalacios** [georgeshirreff/multiNe#13]
Hi @georgeshirreff , @rebzzy  and @ewersSaucedo 

I haven't been able to run 
install_github("georgeshirreff/multiNe")

without errors.

I tried to compile it too but  I get this error:
- checking for sufficient/correct file permissions ... OK
- checking whether package ‘multiNe’ can be installed ... ERROR
  Installation failed.
  See ‘/private/var/folders/jf/dyf0dyk15rj2wbvwnjf7fh2m0000gn/T/RtmpQ4HsV1/multiNe.Rcheck/00install.out’ for details.
- DONE

Status: 1 ERROR
See
  ‘/private/var/folders/jf/dyf0dyk15rj2wbvwnjf7fh2m0000gn/T/RtmpQ4HsV1/multiNe.Rcheck/00check.log’
for details.

after document() and then check(). Please help!!

**Comment by rebzzy** [comment]
When I run that command, I get an error saying that simG.Rd has an empty title

**Comment by JuliaPalacios** [comment]
Yes!! I do too it don't know how to fix it

**Comment by EwersAquaGenomics** [comment]
Can you try again?

C

**Comment by EwersAquaGenomics** [comment]
I think I fixed it.

**Comment by JuliaPalacios** [comment]
It work! Great! Thank you!
