### ISSUE TITLE
rmetasim2adegenet

### ISSUE THREAD

**Issue by rebzzy** [georgeshirreff/multiNe#7]
Hey @ewersSaucedo @georgeshirreff @JuliaPalacios -

Starting to work on the ms and I'm getting some hang ups with nonexistent files (rmetasim2adegenet.R) and some other stuff. I can work through all the bugs but just wanted to make sure you all have pushed your most recent stuff before troubleshooting. 

Thanks!

**Comment by JuliaPalacios** [comment]
Hi Rebecca,
I am a little behind and should be ready by the end of this week but I'll
try harder to finish earlier.

Best,
Julia

**Comment by EwersAquaGenomics** [comment]
Hey Rebecca,
Thanks for picking this up! I have pushed everything decent into the package. Let me check on the missing function though.

The functions should compute results but the results are still incorrect (something is messed up during the calculation)...

Christine

**Comment by rebzzy** [comment]
Hey @ewersSaucedo 

Awesome. I plan to work through everyone's code so I fully know what's going on. I can see if I can find the error. Do you have an expected input/output I can use as a test?

R
