### ISSUE TITLE
authorship?

### ISSUE THREAD

**Issue by JuliaPalacios** [georgeshirreff/multiNe#8]
Hi @georgeshirreff , @rebzzy  and @ewersSaucedo 

Any thoughts about the authorship order? I think Rebecca should be first author since she is writing the paper, what are your thoughts?

**Comment by EwersAquaGenomics** [comment]
I absolutely agree! And I think you, Julia, should be last author because you keep us on track ;) I am happy in the middle.

Christine

**Comment by JuliaPalacios** [comment]
Hi!
Thanks for proposing having me as "senior" but I don't really feel as such so if you don't mind having me in the middle too, I'll be happy to do so. Another alternative could be having Rebecca and then the rest of us with (contributed equally) and in alphabetic order. What are your thoughts?
Julia

**Comment by EwersAquaGenomics** [comment]
That works for me. So the order would be: Rebecca, Christine, Julia and George, right?

**Comment by JuliaPalacios** [comment]
That works for me!

**Comment by georgeshirreff** [comment]
That's fine with me!

George

**Comment by rebzzy** [comment]
Wow - thanks! I definitely won't say no to first author but I'd totally be okay if someone else wanted to claim the spot.
R

**Comment by EwersAquaGenomics** [comment]
In my opinion, who writes the MS gets first authorship :)

**Comment by georgeshirreff** [comment]
My apologies, as discussed before my colleague Lucy Li needs to be on the
paper too as she wrote some of the code I used. In which case it would be
Rebecca, Christine, Lucy (Li), Julia, George. Is that ok with everyone?

George
